name: 'Terror-Form'
description: 'A GitHub Action create markdown diffs from your Terraform plan'

author: 'Felix Bjært Hargreaves'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  plan-json:
    description: 'The Terraform plan as JSON'
    required: true
  should-update-task-summary:
    description:
      'Update the task summary with the diff markdown if set to `true`'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  diff-as-markdown:
    description: 'The diff as markdown'

runs:
  using: node20
  main: dist/index.js
